// export const BASE_URL = "http://localhost:8080"
export const BASE_URL = "http://10.190.64.73:8080"
export const AUTH_URL = "api/v1/auth"
export const LOGIN_URL = "login"
export const REGISTER_URL = 'register';
export const USER_URL = 'apis/users';
export const CURRENT_USER_URL = 'current_user'
export const GET_ALL_PRODUCTS = 'get_all_products'
export const GET_CURRENT_PRODUCT = 'get_product';
export const ADD_PRODUCT_TO_CART = 'add_to_cart'
export const GET_CART_PRODUCTS = 'get_cart_product'
export const UNSELECT_PRODUCT_FROM_CART = 'unselect'
export const CHECKOUT = 'checkout'
export const ADD_ADDRESS = 'setaddress';
export const PAY = 'pay';